### ISSUE TITLE
building simplify example

### ISSUE THREAD

**Issue by stafen123** [Geodan/building-boundary#3]
hello.  Could you give me an example of how to regularize buildings? There are so many functions here that I can't use them very well.

**Comment by chrislcs** [comment]
At the moment this is all very much in development. You can use it if you want, of course, but I can't provide any support or give any guarantees on the output. Most of the functions are documented (though some of it might be out of date, since it still changes all the time). The main function `trace_boundary` is in `trace.py`.

**Comment by skyimager** [comment]
Hi, 

I tried using your code. It fails at "import concave_hull" as no library is found. Could you guide me how to get that library?

**Comment by chrislcs** [comment]
That library can be found here: https://github.com/Geodan/concave-hull. However you could also delete the part of the code that uses it and use the alpha shape method that is also implemented instead. 

As I mentioned before I can't really provide any support or give any guarantees on the output (yet).
